"""Populate Talon's built-in key lists with the documented defaults.

Source: https://talonvoice.com/docs/reference/globals.lists.html#namespace-global
"""

from talon import Context

ctx = Context()


ctx.lists['letter'] = {
    'alpha': 'a',
    'bravo': 'b',
    'charlie': 'c',
    'delta': 'd',
    'echo': 'e',
    'foxtrot': 'f',
    'golf': 'g',
    'hotel': 'h',
    'india': 'i',
    'juliet': 'j',
    'kilo': 'k',
    'lima': 'l',
    'mike': 'm',
    'november': 'n',
    'oscar': 'o',
    'papa': 'p',
    'quebec': 'q',
    'romeo': 'r',
    'sierra': 's',
    'tango': 't',
    'uniform': 'u',
    'victor': 'v',
    'whiskey': 'w',
    'xray': 'x',
    'yankee': 'y',
    'zulu': 'z',
}


ctx.lists['modifier'] = {
    'control': 'ctrl',
    'alt': 'alt',
    'option': 'alt',
    'shift': 'shift',
    'command': 'super',
    'super': 'super',
}


ctx.lists['special_key'] = {
    'delete': 'backspace',
    'end': 'end',
    'enter': 'enter',
    'escape': 'escape',
    'forward delete': 'delete',
    'home': 'home',
    'insert': 'insert',
    'menu key': 'menu',
    'minus': 'minus',
    'page down': 'pagedown',
    'page up': 'pageup',
    'print screen': 'printscr',
    'return': 'return',
    'space': 'space',
    'tab': 'tab',
    'wipe': 'backspace',
    'down': 'down',
    'left': 'left',
    'right': 'right',
    'up': 'up',
    'f one': 'f1',
    'f two': 'f2',
    'f three': 'f3',
    'f four': 'f4',
    'f five': 'f5',
    'f six': 'f6',
    'f seven': 'f7',
    'f eight': 'f8',
    'f nine': 'f9',
    'f ten': 'f10',
    'f eleven': 'f11',
    'f twelve': 'f12',
    'f thirteen': 'f13',
    'f fourteen': 'f14',
    'f fifteen': 'f15',
    'f sixteen': 'f16',
    'f seventeen': 'f17',
    'f eighteen': 'f18',
    'f nineteen': 'f19',
    'f twenty': 'f20',
    'f twenty one': 'f21',
    'f twenty two': 'f22',
    'f twenty three': 'f23',
    'f twenty four': 'f24',
    'key pad zero': 'keypad_0',
    'key pad one': 'keypad_1',
    'key pad two': 'keypad_2',
    'key pad three': 'keypad_3',
    'key pad four': 'keypad_4',
    'key pad five': 'keypad_5',
    'key pad six': 'keypad_6',
    'key pad seven': 'keypad_7',
    'key pad eight': 'keypad_8',
    'key pad nine': 'keypad_9',
    'key pad clear': 'keypad_clear',
    'key pad enter': 'keypad_enter',
    'key pad equals': 'keypad_equals',
    'key pad minus': 'keypad_minus',
    'key pad plus': 'keypad_plus',
    'key pad point': 'keypad_decimal',
    'key pad slash': 'keypad_divide',
    'key pad star': 'keypad_multiply',
}


ctx.lists['symbol'] = {
    'back tick': '`',
    'caret': '^',
    'comma': ',',
    'equals': '=',
    'grave': '`',
    'pipe': '|',
    'plus': '+',
    'tilde': '~',
    'dot': '.',
    'full stop': '.',
    'period': '.',
    'point': '.',
    'colon': ':',
    'semicolon': ';',
    'question mark': '?',
    'question': '?',
    'exclamation mark': '!',
    'exclamation point': '!',
    'asterisk': '*',
    'star': '*',
    'hash sign': '#',
    'number sign': '#',
    'percent sign': '%',
    'percent': '%',
    'at sign': '@',
    'at symbol': '@',
    'amper': '&',
    'ampersand': '&',
    'and sign': '&',
    'dash': '-',
    'hyphen': '-',
    'minus': '-',
    'down score': '_',
    'underscore': '_',
    'forward slash': '/',
    'slash': '/',
    'backslash': '\\',
    'left paren': '(',
    'paren': '(',
    'right paren': ')',
    'bracket': '[',
    'left bracket': '[',
    'right bracket': ']',
    'brace': '{',
    'curly bracket': '{',
    'left curly bracket': '{',
    'right brace': '}',
    'right curly bracket': '}',
    'angle bracket': '<',
    'left angle bracket': '<',
    'less than': '<',
    'greater than': '>',
    'right angle bracket': '>',
    'apostrophe': "'",
    'double quote': '"',
    'quote': "'",
    'dollar sign': '$',
    'dollar': '$',
    'pound sign': '£',
    'pound': '£',
}
